---
# - hosts: all
#   roles:
#     - { role: kubernetes/preinstall, tags: preinstall }

- hosts: kube-master[0]
  roles:
    # - role: multirack/bird-container
    #   bgpd_mode: rr
    #   bgpd_container_tag: latest
    #   etcd_endpoints: "{{ groups.etcd }}"
    #   tags: network
    - { role: multirack/upload-config, tags: network }

- hosts: kube-master
  roles:
    - role: multirack/bird-container
      bgpd_mode: rr
      bgpd_container_tag: latest
      etcd_endpoint: "{{ groups.etcd[0] }}"
      tags: network

- hosts: kube-node #:!k8s-cluster
  roles:
    - role: multirack/bird-container
      bgpd_mode: node
      bgpd_container_tag: latest
      etcd_endpoint: "{{ groups.etcd[0] }}"
      tags: network

