---
# - hosts: all
#   roles:
#     - { role: kubernetes/preinstall, tags: preinstall }

- hosts: kube-master[0]
  roles:
    - role: multirack/upload-config
      etcd_authority: "{%for a in groups.etcd%}https://{{a}}:4001/{%if not loop.last%},{%endif%}{%endfor%}"
      tags: network

- hosts: kube-master
  roles:
    - role: multirack/bird-container
      bgpd_mode: rr
      bgpd_container_tag: latest
      etcd_authority: "{%for a in groups.etcd%}https://{{a}}:4001/{%if not loop.last%},{%endif%}{%endfor%}"
      tags: network

- hosts: kube-node #:!k8s-cluster
  roles:
    - role: multirack/bird-container
      bgpd_mode: node
      bgpd_container_tag: latest
      etcd_authority: "{%for a in groups.etcd%}https://{{a}}:4001/{%if not loop.last%},{%endif%}{%endfor%}"
      tags: network

