---
- generate_multirack_topology: inventory="{% for host in groups['all'] %}{{ hostvars[host]|to_json }}{% endfor %}"
  register: multirack_topology
#- debug: var=multirack_topology
- copy: dest=/tmp/multirack_topology.json content="{{multirack_topology}}" mode=644
  register: multirack_topology_file
- command: etcdtool -p "\"{{etcd_authority}}\"" import -y -f json /multirack_topology /tmp/multirack_topology.json
  when: multirack_topology_file.changed
