---
- generate_multirack_topology: inventory="{% for host in groups['all'] %}{{ hostvars[host]|to_json }}{% endfor %}"
  register: multirack_topology
#- debug: var=multirack_topology
- copy: dest={{multirack_topology_tmp_file}} content="{{multirack_topology}}" mode=644
  register: multirack_topology_file
- command: etcdtool -p "{{etcd_authority}}" import -y -f json /multirack_topology {{multirack_topology_tmp_file}}
  when: multirack_topology_file.changed
  register: multirack_topology_uploaded
- file: path=multirack_topology_tmp_file state=absent
  when: multirack_topology_uploaded|failed
