---
#- debug: var=multirack_topology
- name: Install addition packages
  apt: name={{item}} state=latest
  with_items:
    - docker.io
    - python-docker
- name: Download Route Redistributer container
  docker_image: name=xenolog/k8s-rr-container:latest
- block:
  - name: Configure and run RR
    template:
      src: bird-rr_env.j2
      dest: /etc/bird-rr.env
    notify: restart bird-rr
  - template:
      src: bird-rr_systemd_unit.j2
      dest: /etc/systemd/system/bird-rr.service
    notify:
     - reload systemd
     - restart bird-rr
  - service: name=bird-rr enabled=yes state=started
